//Generated by Google AI, not sure I trust it

import themidibus.*; // Import the MidiBus library

MidiBus myBus; // Create a MidiBus object

void setup() {
  size(400, 400);
  background(0);
  
  // List all available MIDI devices in the console
  MidiBus.list(); 
  
  // Initialize the bus:
  // Argument 1: Parent sketch (this)
  // Argument 2: Incoming device index or name (e.g., 0, or "Your Keyboard Name")
  // Argument 3: Outgoing device index or name (-1 for none)
  myBus = new MidiBus(this, 1, -1); 
}

void draw() {
  // Your visual code here
}

// --- CALLBACK FUNCTIONS ---

//Allegedly these just get called automatically??

// 1. Automatically called when a Note On message is received
void noteOn(int channel, int pitch, int velocity) {
  println("Note On - Channel: " + channel + " | Pitch: " + pitch + " | Velocity: " + velocity);
}

// 2. Automatically called when a Note Off message is received
void noteOff(int channel, int pitch, int velocity) {
  println("Note Off - Channel: " + channel + " | Pitch: " + pitch + " | Velocity: " + velocity);
}

// 3. Automatically called when a Control Change (knobs/faders) is moved
void controllerChange(int channel, int number, int value) {
  println("Control Change - Channel: " + channel + " | Number: " + number + " | Value: " + value);
}
